name: huchao
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  dio: ">=3.0.4 <6.0.0"
  async: ^2.3.0
  flutter_screenutil: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/door.png
    - images/kitchen.png
    - images/camera.png
    - images/number.jpg
    - images/alert.png
    - images/Old-Man.png


